### ISSUE TITLE
OAL Logos Improperly Scaling

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/Icons#51]
**Describe the bug**
Various partner airlines are not scaling as expected 

**To Reproduce**
https://components.alaskaair.com/catelog/demo/airline-helper
See all logos that are improperly displayed. Expecting these SVGs to scale out to the edges of the container.

**Expected behavior**
SVG fills container
![image](https://user-images.githubusercontent.com/7005799/101110609-3671fc00-358e-11eb-9f35-9684ebb3f5a6.png)

**Screenshots**

Impacted logos:
BA, AY, HU, HA, QF, LH, JL, DE, DL, FI, AM
Should we consider moving the "Pacific" under "Cathay" for CX, as well as "airlines" for JL?
![image](https://user-images.githubusercontent.com/7005799/101110196-59e87700-358d-11eb-89e3-5f1fdeaf5326.png)
![image](https://user-images.githubusercontent.com/7005799/101110238-6bca1a00-358d-11eb-968a-43abcfbca2d3.png)
![image](https://user-images.githubusercontent.com/7005799/101110245-708ece00-358d-11eb-9996-1943d3e11867.png)
![image](https://user-images.githubusercontent.com/7005799/101110255-75538200-358d-11eb-8081-5dd2e75e1186.png)
![image](https://user-images.githubusercontent.com/7005799/101110267-7ab0cc80-358d-11eb-8bae-c0262926b073.png)
![image](https://user-images.githubusercontent.com/7005799/101110278-800e1700-358d-11eb-9a13-fd70604fffe3.png)
![image](https://user-images.githubusercontent.com/7005799/101110294-87cdbb80-358d-11eb-9dd1-4c292532e5c3.png)
![image](https://user-images.githubusercontent.com/7005799/101110307-8f8d6000-358d-11eb-9bae-650157f02c7e.png)
![image](https://user-images.githubusercontent.com/7005799/101110323-95834100-358d-11eb-8d2a-40f5815b3ce2.png)
![image](https://user-images.githubusercontent.com/7005799/101110330-9b792200-358d-11eb-89f6-c3ffa8e8cf04.png)
![image](https://user-images.githubusercontent.com/7005799/101110338-a0d66c80-358d-11eb-9aaf-3a86a8427c08.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blackfalcon** [comment]
Issue accidentally associated with unrelated PR.

**Comment by blackfalcon** [comment]
Here is what I have come up with in regards to this issue. Here is a demo page of all the logos http://ota-logo.surge.sh/ota

In your code you are brute-forcing the width and the height of the SVG and that's not going to work. Not any of these SVGs have the same viewBox dimensions. Because of that, there is no way that you can do what you are trying to do. 

Notice in the demo I am only restricting the `width` and some of the boxes have heights. That is because the height is baked into the viewBox of the SVG and that will be a LOT OF WORK to try and edit those by hand on code. 

I'd suggest a couple of things to try here. 

1. I'd put a `div` around the SVG and control the size of that, not the SVG itself. That way you don't need to use all those `important` statements. 
1. If you can, use the auro-icon component and you can address the size of that container versus a `div`. 

In the end, these SVGs and this design pattern are pretty incompatible. I feel like there is a better design solution somewhere for this.

**Comment by blackfalcon** [comment]
This issue has been taken up by the design team to normalize the OTA logos.

**Comment by blackfalcon** [comment]
I am assuming that the solution to this logo issue is the new tail icons? If that is so, am I to assume that the logos can be removed from the lib?

**Comment by gusnaughton** [comment]
That is the solution, but we will be in production with the fullsize logos on the matrix page (not the details modal like we discussed) for several months. I will let you know once we retire that old experience so we can remove it here.

**Comment by blackfalcon** [comment]
If that is the case, I am going to close this issue as there is no point in keeping this open for months. When the time comes to remove the legacy logos, we can create a new issue at that time.
